package com.libreria.form;

import com.libreria.connection.Conexion;
import com.libreria.connection.DatabaseConnection;
import com.libreria.main.RenderImagen;
import com.libreria.model.ModelProduct;
import com.libreria.service.ServiceProductos;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabia
 */
public class Vista_Productos extends javax.swing.JInternalFrame {

    Conexion con = new Conexion();
    DatabaseConnection can;
    private ServiceProductos sp;
    DefaultTableModel mModeloTabla = new DefaultTableModel();

    public Vista_Productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void CargarImagenes() {
        tblImagenes.setDefaultRenderer(Object.class, new RenderImagen());

        ArrayList productos;
        ModelProduct producto;
        sp = new ServiceProductos();
        
            Object Datos[] = new Object[3];
            productos = sp.getAll();
            
            if (productos != null) {
                for (int i = 0; i < productos.size(); i++) {
                    producto = (ModelProduct) productos.get(i);
                    Datos[0] = String.valueOf(producto.getId());
                    Datos[1] = producto.getNombre();
                    
                    try {
                        byte[] imagen = producto.getImagen();
                        BufferedImage bufferedImage = null;
                        InputStream inputStream = new ByteArrayInputStream(imagen);
                        bufferedImage = ImageIO.read(inputStream);
                        ImageIcon mIcono = new ImageIcon(bufferedImage.getScaledInstance(60, 60, 0));
                        Datos[2] = new JLabel(mIcono);
                    } catch (Exception e) {
                        Datos[2] = new JLabel("No imagen");
                    }

                    mModeloTabla.addRow(Datos);
                }

                tblImagenes.setModel(mModeloTabla);
                tblImagenes.setRowHeight(60);
                tblImagenes.getColumnModel().getColumn(0).setPreferredWidth(60);
                tblImagenes.getColumnModel().getColumn(1).setPreferredWidth(60);
                tblImagenes.getColumnModel().getColumn(2).setPreferredWidth(60);

            }
        

    }
    private void Limpiar() {
        for (int i = 0; i < tblImagenes.getRowCount(); i++) {
            mModeloTabla.removeRow(i);
            i -= 1;
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblImagenes = new javax.swing.JTable();

        tblImagenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblImagenes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(52, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblImagenes;
    // End of variables declaration//GEN-END:variables
}
